name: Check database Changes

on:
    pull_request:
        branches:
            - main
        types:
            - opened
            - reopened
            - synchronize
            - ready_for_review
        paths:
            - src/db/**

jobs:
    check-db-changes:
        if: ${{ !github.event.pull_request.draft }}
        runs-on: ubuntu-latest
        permissions:
            pull-requests: write
        steps:
            # Delete functionality can be added once https://github.com/thollander/actions-comment-pull-request/pull/371 is merged
            - name: Post a reminder comment
              uses: thollander/actions-comment-pull-request@v2.5.0
              with:
                  message: |
                      🚨 **Reminder:** The database seems to have been modified.
                      Please ensure all relevant files are updated accordingly.
                      Don't forget to run the `dbml.ts` script to generate a new schema and to generate the new DB migrations (one migration per PR please).
